_Z33Pml_PokePara_Factory__FixInitSpecP26Pml_PokePara_InitialSpec_oS0_PK10MethodInfo = 0x23B6910 - 0x545F000; /* void Pml_PokePara_Factory__FixInitSpec(Pml_PokePara_InitialSpec_o * pFixSpec, Pml_PokePara_InitialSpec_o * spec, const MethodInfo * method) */
_Z26Pml_Local_Random__GetValuePK10MethodInfo = 0x269B8A0 - 0x545F000; /* uint32_t Pml_Local_Random__GetValue(const MethodInfo * method) */
_Z26Pml_Local_Random__GetValuejPK10MethodInfo = 0x269BA10 - 0x545F000; /* uint32_t Pml_Local_Random__GetValue(uint32_t max, const MethodInfo * method) */

_Z30RandomGroupWork__GetRandomSeediPK10MethodInfo = 0x1F60FB0 - 0x545F000; /* uint64_t RandomGroupWork__GetRandomSeed(int32_t no, const MethodInfo * method) */
_Z30RandomGroupWork__SetRandomSeedimPK10MethodInfo = 0x1F60DC0 - 0x545F000; /* void RandomGroupWork__SetRandomSeed(int32_t no, uint64_t seed, const MethodInfo * method) */
_Z28RandomGroupWork__RandomRangeiiPK10MethodInfo = 0x1F60AA0 - 0x545F000; /* int32_t RandomGroupWork__RandomRange(int32_t min, int32_t max, const MethodInfo * method) */
_Z24PlayerWork__get_uniqueIDPK10MethodInfo = 0x1BB7D20 - 0x545F000; /* uint32_t PlayerWork__get_uniqueID(const MethodInfo * method) */

_Z32GameManager__GetFieldEncountDataiPK10MethodInfo = 0x1E366D0 - 0x545F000; /* XLSXContent_FieldEncountTable_Sheettable_o * GameManager__GetFieldEncountData(int32_t zoneid, const MethodInfo * method) */

_Z26PlayerWork__get_playerDataPK10MethodInfo = 0x1BBB580 - 0x545F000; /* DPData_PLAYER_DATA_o * PlayerWork__get_playerData(const MethodInfo * method) */
_Z24GameManager__get_mapInfoPK10MethodInfo = 0x1E2FD00 - 0x545F000; /* XLSXContent_MapInfo_o * GameManager__get_mapInfo(const MethodInfo * method) */
_Z29TrainerSystem__GetTrainerDataiPK10MethodInfo = 0x1CD7420 - 0x545F000; /* XLSXContent_TrainerTable_SheetTrainerData_o * TrainerSystem__GetTrainerData(int32_t trainerID, const MethodInfo * method) */
_Z29TrainerSystem__GetTrainerPokeiPK10MethodInfo = 0x1CD75A0 - 0x545F000; /* XLSXContent_TrainerTable_SheetTrainerPoke_o * TrainerSystem__GetTrainerPoke(int32_t trainerID, const MethodInfo * method) */


_Z32Pml_PokePara_PokemonParam___ctorP27Pml_PokePara_PokemonParam_oitmPK10MethodInfo = 0x23B8130 - 0x545F000; /* void Pml_PokePara_PokemonParam___ctor(Pml_PokePara_PokemonParam_o * __this, int32_t monsno, uint16_t level, uint64_t id, const MethodInfo * method) */
_Z29PlayerWork__get_defaultPokeNoPK10MethodInfo = 0x1BBBBB0 - 0x545F000; /* int32_t PlayerWork__get_defaultPokeNo(const MethodInfo * method) */
_Z27PlayerWork__get_rivalPokeNoPK10MethodInfo = 0x1BBBF30 - 0x545F000; /* int32_t PlayerWork__get_rivalPokeNo(const MethodInfo * method) */
_Z29PlayerWork__get_supportPokeNoPK10MethodInfo = 0x1BBC1A0 - 0x545F000; /* int32_t PlayerWork__get_supportPokeNo(const MethodInfo * method) */
