_Z33Pml_PokePara_Factory__FixInitSpecP26Pml_PokePara_InitialSpec_oS0_PK10MethodInfo = 0x23B6910 - 0x545F000; /* void Pml_PokePara_Factory__FixInitSpec(Pml_PokePara_InitialSpec_o * pFixSpec, Pml_PokePara_InitialSpec_o * spec, const MethodInfo * method) */
_Z26Pml_Local_Random__GetValuePK10MethodInfo = 0x269B8A0 - 0x545F000; /* uint32_t Pml_Local_Random__GetValue(const MethodInfo * method) */
_Z26Pml_Local_Random__GetValuejPK10MethodInfo = 0x269BA10 - 0x545F000; /* uint32_t Pml_Local_Random__GetValue(uint32_t max, const MethodInfo * method) */

_Z30RandomGroupWork__GetRandomSeediPK10MethodInfo = 0x1F60FB0 - 0x545F000; /* uint64_t RandomGroupWork__GetRandomSeed(int32_t no, const MethodInfo * method) */
_Z30RandomGroupWork__SetRandomSeedimPK10MethodInfo = 0x1F60DC0 - 0x545F000; /* void RandomGroupWork__SetRandomSeed(int32_t no, uint64_t seed, const MethodInfo * method) */
_Z28RandomGroupWork__RandomRangeiiPK10MethodInfo = 0x1F60AA0 - 0x545F000; /* int32_t RandomGroupWork__RandomRange(int32_t min, int32_t max, const MethodInfo * method) */
_Z24PlayerWork__get_uniqueIDPK10MethodInfo = 0x1BB7D20 - 0x545F000; /* uint32_t PlayerWork__get_uniqueID(const MethodInfo * method) */

_Z32GameManager__GetFieldEncountDataiPK10MethodInfo = 0x1E366D0 - 0x545F000; /* XLSXContent_FieldEncountTable_Sheettable_o * GameManager__GetFieldEncountData(int32_t zoneid, const MethodInfo * method) */

_Z26PlayerWork__get_playerDataPK10MethodInfo = 0x1BBB580 - 0x545F000; /* DPData_PLAYER_DATA_o * PlayerWork__get_playerData(const MethodInfo * method) */

_Z24GameManager__get_mapInfoPK10MethodInfo = 0x1E2FD00 - 0x545F000; /* XLSXContent_MapInfo_o * GameManager__get_mapInfo(const MethodInfo * method) */
