_Z33Pml_PokePara_Factory__FixInitSpecP26Pml_PokePara_InitialSpec_oS0_PK10MethodInfo = 0x20DAEE0 - 0x56C1000; /* void Pml_PokePara_Factory__FixInitSpec(Pml_PokePara_InitialSpec_o * pFixSpec, Pml_PokePara_InitialSpec_o * spec, const MethodInfo * method) */

_Z26Pml_Local_Random__GetValuePK10MethodInfo = 0x258B910 - 0x56C1000; /* uint32_t Pml_Local_Random__GetValue(const MethodInfo * method) */
_Z26Pml_Local_Random__GetValuejPK10MethodInfo = 0x258BA80 - 0x56C1000; /* uint32_t Pml_Local_Random__GetValue(uint32_t max, const MethodInfo * method) */

_Z30RandomGroupWork__GetRandomSeediPK10MethodInfo = 0x1AD4060 - 0x56C1000; /* uint64_t RandomGroupWork__GetRandomSeed(int32_t no, const MethodInfo * method) */
_Z30RandomGroupWork__SetRandomSeedimPK10MethodInfo = 0x1AD3D70 - 0x56C1000; /* void RandomGroupWork__SetRandomSeed(int32_t no, uint64_t seed, const MethodInfo * method) */
_Z28RandomGroupWork__RandomRangeiiPK10MethodInfo = 0x1AD3A40 - 0x56C1000; /* int32_t RandomGroupWork__RandomRange(int32_t min, int32_t max, const MethodInfo * method) */
_Z24PlayerWork__get_uniqueIDPK10MethodInfo = 0x1FE6B40 - 0x56C1000; /* uint32_t PlayerWork__get_uniqueID(const MethodInfo * method) */

_Z32GameManager__GetFieldEncountDataiPK10MethodInfo = 0x1A72BD0 - 0x56C1000; /* XLSXContent_FieldEncountTable_Sheettable_o * GameManager__GetFieldEncountData(int32_t zoneid, const MethodInfo * method) */

_Z26PlayerWork__get_playerDataPK10MethodInfo = 0x1FDC3A0 - 0x56C1000; /* DPData_PLAYER_DATA_o * PlayerWork__get_playerData(const MethodInfo * method) */
_Z24GameManager__get_mapInfoPK10MethodInfo = 0x1A6C230 - 0x56C1000; /* XLSXContent_MapInfo_o * GameManager__get_mapInfo(const MethodInfo * method) */
_Z29TrainerSystem__GetTrainerDataiPK10MethodInfo = 0x18B7E90 - 0x56C1000; /* XLSXContent_TrainerTable_SheetTrainerData_o * TrainerSystem__GetTrainerData(int32_t trainerID, const MethodInfo * method) */
_Z29TrainerSystem__GetTrainerPokeiPK10MethodInfo = 0x18B8010 - 0x56C1000; /* XLSXContent_TrainerTable_SheetTrainerPoke_o * TrainerSystem__GetTrainerPoke(int32_t trainerID, const MethodInfo * method) */


_Z32Pml_PokePara_PokemonParam___ctorP27Pml_PokePara_PokemonParam_oitmPK10MethodInfo = 0x20DC700 - 0x56C1000; /* void Pml_PokePara_PokemonParam___ctor(Pml_PokePara_PokemonParam_o * __this, int32_t monsno, uint16_t level, uint64_t id, const MethodInfo * method) */
_Z29PlayerWork__get_defaultPokeNoPK10MethodInfo = 0x1FEA960 - 0x56C1000; /* int32_t PlayerWork__get_defaultPokeNo(const MethodInfo * method) */
_Z27PlayerWork__get_rivalPokeNoPK10MethodInfo = 0x1FEACE0 - 0x56C1000; /* int32_t PlayerWork__get_rivalPokeNo(const MethodInfo * method) */
_Z29PlayerWork__get_supportPokeNoPK10MethodInfo = 0x1FEAF50 - 0x56C1000; /* int32_t PlayerWork__get_supportPokeNo(const MethodInfo * method) */
